### PR TITLE
Update all the things.

### PR DESCRIPTION
**Pull request by dblock**
Spidey doesn't look maintained, but it works great and is super useful. Coming from  https://github.com/dblock/slack-api-ref/pull/4. Lets update all the things and revive it a bit.

### CODE REVIEW

**Comment by rusikf** [comment]
:+1:

**Comment by joeyAghion** [comment]
Ha ha. It's true... how can we distinguish unmaintained projects from those that just work?

I like all of this except Rubocop... care to leave that out, or separate the PRs? I think it adds too high a bar and unfamiliar tools for a small gem like this, where the maintainers should be able to enforce conventions or make exceptional judgment calls.

**Comment by dblock** [comment]
I'll take it out. But I like enforcing style with a tool rather than a free for all. It autocorrects obvious mistakes and such. Lmk if you change your mind.

**Comment by dblock** [comment]
Closing in favor of #6.

**Comment by joeyAghion** [comment]
Thanks. If others are in favor of keeping Rubocop, by all means chime in here.

**Pull request closed without merging**
